### ISSUE TITLE
1.21 Crash on latest 2.0.2 version 

### ISSUE THREAD

**Issue by yichifauzi** [IMB11/SkinShuffle#80] opened 2024-07-03 12:53 UTC
### Describe the issue

when using these mods below crash on start

 fabric-api-0.100.4+1.21
 modmenu-11.0.1
 placeholder-api-2.4.0+1.21
 SkinShuffle-2.0.2+1.21

### Relevant log output

https://mclo.gs/GMUXiDK

### SkinShuffle version

2.0.2

**Comment by yichifauzi** [comment] 2024-07-03 12:55
nevermind just start again it fixed lol

**Comment by yichifauzi** [comment] 2024-07-03 13:06
https://mclo.gs/N8Fa8qW
Oooopss crash again when click skin preset

**Comment by IMB11** [comment] 2024-07-03 14:35
NativeImage strikes again ugh - will investigate.

**Comment by IMB11** [comment] 2024-07-09 16:35
Going to merge this into one big issue.

Duplicate of #86

**Closed by IMB11** 2024-07-09 16:35 UTC
Labels: Bug/Crash
